// Supabase → Project Settings → API
window.SUPABASE_URL = 'https://lsoieljknndrtsyeolbd.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzb2llbGprbm5kcnRzeWVvbGJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0NjQxNjMsImV4cCI6MjA5NTA0MDE2M30.5v3QARkAzFSnkEcfIaos9h5YxB9doDO6sRtRIqdtJ_E';
